import json

def ph(*args):
    return {'placeholders': {name: {'type': typ} for name, typ in args}}

# Run: python tool/add_log_err_keys.py

log_en = {
  'logUnlockZip': 'Unlocked ZIP: {name}',
  'logUnlockError': 'Unlock error: {error}',
  'logEnableManageStorage': 'Enable All files access in Settings',
  'logGrantedAllFilesAccess': 'All-files access granted',
  'logEnableManageAllFiles': 'Enable manage all files access in Settings',
  'logNewTab': 'New tab: {name}',
  'logFileLocation': 'Location: {path}',
  'logViewZip': 'View ZIP: {name}',
  'logRecentAdded': 'Added {count} recent files',
  'logRecentScanned': 'Scanned {count} recent files',
  'logRecentScanError': 'Recent scan error: {error}',
  'logAppsAdded': 'Added {count} apps ({type})',
  'logAppsLoaded': 'Loaded {count} apps',
  'logAppsLoadError': 'App load error: {error}',
  'logAppsTypeSystem': 'system',
  'logAppsTypeUser': 'user',
  'logReadItemsRoot': 'Read {count} items at Root',
  'logReadItemsAt': 'Read {count} items at {location}',
  'logReadError': 'Read error {location}: {error}',
  'logOpenAppInfo': 'Opening app info',
  'logOpenAppInfoError': 'App info error: {error}',
  'logApkCopied': 'APK copied: {name}',
  'logApkCopyError': 'APK copy error: {error}',
  'logApkShared': 'APK shared: {name}',
  'logApkShareError': 'APK share error: {error}',
  'logPlayStoreError': 'Play Store error: {error}',
  'logApkBackup': 'APK backed up → {path}',
  'logApkBackupError': 'APK backup error: {error}',
  'logUninstall': 'Uninstall: {name}',
  'logUninstallError': 'Uninstall error: {error}',
  'logLaunchApp': 'Launch app: {package}',
  'logOpenAppError': 'Open app error: {error}',
  'logHomeLoadError': 'Home load error: {error}',
  'logFtpError': 'FTP error: {error}',
  'logZipReadError': 'ZIP read error: {error}',
  'logFileOpened': 'Opened {name}',
  'logFormatNotSupportedOpen': 'Format {format} is not supported.',
  'logFtpFileLoadError': 'FTP file load error: {error}',
  'logCreateFile': 'Created file: {name}',
  'logCreateFolder': 'Created folder: {name}',
  'logCopiedItems': 'Copied {count} items',
  'logCutItems': 'Cut {count} items',
  'logCannotPasteInZip': 'Cannot paste inside ZIP',
  'logPasteSuccess': 'Paste successful',
  'logPasteError': 'Paste error: {error}',
  'logDuplicateSuccess': 'Duplicated {count} items',
  'logDuplicateError': 'Duplicate error: {error}',
  'logDeletePartialNotice': 'Deleted items cannot be restored. Remaining items were not deleted.',
  'logMovedToTrash': 'Moved {count} items to trash',
  'logDeletedItems': 'Deleted {count} items',
  'logDeleteError': 'Delete error: {error}',
  'logRenamedTo': 'Renamed to {name}',
  'logZippedTo': 'Compressed to {name}',
  'logUnzipTo': 'Extracted to {folder}',
  'logUnzipError': 'Extract error: {error}',
  'logApkNotFound': 'APK file not found',
  'logInstallApkError': 'APK install error: {error}',
  'logOpeningFromZip': 'Opening file from ZIP...',
  'logPrepareShareFromZip': 'Preparing to share file from ZIP...',
  'logShareFileError': 'Share file error: {error}',
  'logFormatNotSupportedDirect': 'Format {format} is not supported for direct extraction.',
  'logFileSaved': 'Saved {name}',
  'logSaveError': 'Save error: {error}',
  'logWebServerStarted': 'Web server{auth}: {url}{scope}',
  'logWebServerAuthWith': ' (password)',
  'logWebServerScopeFolder': ' — folder: {path}',
  'logWebServerScopeAll': ' — entire storage',
  'logWebServerStartError': 'Web server start error: {error}',
  'logWebServerStopped': 'Web server stopped',
  'logZipError': 'ZIP error: {error}',
}

log_vi = {
  'logUnlockZip': 'Đã mở khóa ZIP: {name}',
  'logUnlockError': 'Lỗi mở khóa: {error}',
  'logEnableManageStorage': 'Bật quyền Truy cập tất cả file trong Cài đặt',
  'logGrantedAllFilesAccess': 'Đã cấp quyền truy cập tất cả file',
  'logEnableManageAllFiles': 'Bật Cho phép truy cập để quản lý tất cả tệp trong Cài đặt',
  'logNewTab': 'Tab mới: {name}',
  'logFileLocation': 'Vị trí: {path}',
  'logViewZip': 'Xem ZIP: {name}',
  'logRecentAdded': 'Đã thêm {count} tập tin gần đây',
  'logRecentScanned': 'Đã quét {count} tập tin gần đây',
  'logRecentScanError': 'Lỗi quét tập tin gần đây: {error}',
  'logAppsAdded': 'Đã thêm {count} ứng dụng ({type})',
  'logAppsLoaded': 'Đã tải {count} ứng dụng',
  'logAppsLoadError': 'Lỗi tải ứng dụng: {error}',
  'logAppsTypeSystem': 'hệ thống',
  'logAppsTypeUser': 'người dùng',
  'logReadItemsRoot': 'Đã đọc {count} mục tại Root',
  'logReadItemsAt': 'Đã đọc {count} mục tại {location}',
  'logReadError': 'Lỗi đọc {location}: {error}',
  'logOpenAppInfo': 'Mở thông tin ứng dụng',
  'logOpenAppInfoError': 'Lỗi mở thông tin ứng dụng: {error}',
  'logApkCopied': 'Đã sao chép APK: {name}',
  'logApkCopyError': 'Lỗi sao chép APK: {error}',
  'logApkShared': 'Chia sẻ APK: {name}',
  'logApkShareError': 'Lỗi chia sẻ APK: {error}',
  'logPlayStoreError': 'Lỗi mở Play Store: {error}',
  'logApkBackup': 'Đã backup APK → {path}',
  'logApkBackupError': 'Lỗi backup APK: {error}',
  'logUninstall': 'Gỡ cài đặt: {name}',
  'logUninstallError': 'Lỗi gỡ cài đặt: {error}',
  'logLaunchApp': 'Khởi chạy ứng dụng: {package}',
  'logOpenAppError': 'Lỗi mở ứng dụng: {error}',
  'logHomeLoadError': 'Lỗi tải màn hình chính: {error}',
  'logFtpError': 'Lỗi FTP: {error}',
  'logZipReadError': 'Lỗi đọc ZIP: {error}',
  'logFileOpened': 'Đã mở {name}',
  'logFormatNotSupportedOpen': 'Định dạng {format} chưa được hỗ trợ.',
  'logFtpFileLoadError': 'Lỗi tải tệp FTP: {error}',
  'logCreateFile': 'Tạo file mới: {name}',
  'logCreateFolder': 'Tạo thư mục mới: {name}',
  'logCopiedItems': 'Đã copy {count} mục',
  'logCutItems': 'Đã cut {count} mục',
  'logCannotPasteInZip': 'Không thể paste vào bên trong ZIP',
  'logPasteSuccess': 'Đã dán thành công',
  'logPasteError': 'Lỗi paste: {error}',
  'logDuplicateSuccess': 'Đã nhân đôi {count} mục',
  'logDuplicateError': 'Lỗi nhân đôi: {error}',
  'logDeletePartialNotice': 'Các mục đã xóa không thể khôi phục. Phần còn lại chưa bị xóa.',
  'logMovedToTrash': 'Đã chuyển {count} mục vào thùng rác',
  'logDeletedItems': 'Đã xóa {count} mục',
  'logDeleteError': 'Lỗi xóa: {error}',
  'logRenamedTo': 'Đã đổi tên thành {name}',
  'logZippedTo': 'Đã nén thành {name}',
  'logUnzipTo': 'Đã giải nén vào {folder}',
  'logUnzipError': 'Lỗi giải nén: {error}',
  'logApkNotFound': 'File APK không tồn tại',
  'logInstallApkError': 'Lỗi cài APK: {error}',
  'logOpeningFromZip': 'Đang mở file từ ZIP...',
  'logPrepareShareFromZip': 'Đang chuẩn bị chia sẻ file từ ZIP...',
  'logShareFileError': 'Lỗi chia sẻ file: {error}',
  'logFormatNotSupportedDirect': 'Định dạng {format} chưa được hỗ trợ giải nén trực tiếp.',
  'logFileSaved': 'Đã lưu {name}',
  'logSaveError': 'Lỗi lưu: {error}',
  'logWebServerStarted': 'Web server{auth}: {url}{scope}',
  'logWebServerAuthWith': '',
  'logWebServerScopeFolder': ' — thư mục: {path}',
  'logWebServerScopeAll': ' — toàn bộ bộ nhớ',
  'logWebServerStartError': 'Lỗi bật web server: {error}',
  'logWebServerStopped': 'Đã tắt web server',
  'logZipError': 'Lỗi nén ZIP: {error}',
}

err_en = {
  'errCannotReadZipList': 'Cannot read file list in ZIP',
  'errZipTooLargeVerifyPassword': 'ZIP too large ({sizeMb} MB). Cannot verify password in memory.',
  'errZipAesTooLarge': 'AES-encrypted ZIP too large ({sizeMb} MB). Limit {limitMb} MB.',
  'errZipTooLargeNeedUnzip': 'ZIP too large ({sizeMb} MB). unzip/7z command required on device.',
  'errFlutterArchiveUnavailable': 'flutter_archive is not available on this platform',
  'errCannotExtractZipEntry': 'Cannot extract ZIP entry',
  'errCannotExtractTar': 'Cannot extract TAR',
  'errDataTooLargeCompress': 'Data too large ({sizeMb} MB). Cannot compress in memory.',
  'errMultiFolderZipNoCommand': 'Cannot compress multiple folders — zip command missing on device',
  'errCannotCreateZip': 'Cannot create ZIP file',
  'errParentDirNotFound': 'Parent directory does not exist',
  'errCannotWriteDestDir': 'Cannot write to destination directory',
  'errZipTooLargeExtract': 'ZIP too large ({sizeMb} MB). Native extraction or unzip required.',
  'errZipTooLargeSingleEntry': 'ZIP too large to extract a single entry in RAM',
  'errZipEntryNotFound': 'Entry not found in ZIP',
  'errFileNotExists': 'File does not exist',
  'errInvalidZip': 'Invalid ZIP file',
  'errZipEocdNotFound': 'End of Central Directory not found',
  'errZipCdCorrupt': 'ZIP Central Directory is corrupt',
  'errZipCdTooLarge': 'Central Directory too large ({sizeMb} MB)',
  'errZipCdIncomplete': 'Could not read full Central Directory',
  'errZip64LocatorInvalid': 'Invalid ZIP64 locator',
  'errZip64EocdInvalid': 'Invalid ZIP64 EOCD signature',
  'errZip64EocdOutOfFile': 'ZIP64 EOCD is outside the file',
  'errDirectoryNotExists': 'Directory does not exist',
  'errCannotAccessPath': 'Cannot access {path}: {message}',
  'errAlreadyExists': 'Already exists',
  'errShellListingAndroidOnly': 'Shell listing is only supported on Android',
  'errSuperuserAndroidOnly': 'Superuser mode is only supported on Android',
  'errCannotCheckSuperuser': 'Cannot check superuser access',
  'errSuperuserCheckTimeout': 'Superuser check timed out. Device may not be rooted or access not granted.',
  'errInstallApkAndroidOnly': 'APK install is only supported on Android',
  'errApkNotFound': 'APK not found',
  'errApkBackupFailed': 'Backup failed',
  'errNoWebServerPassword': 'No Web Server password set',
  'errNoPassword': 'No password set',
  'errCurrentPasswordWrong': 'Current password is incorrect',
  'errBiometricUnlockReason': 'Unlock Cope X Studio',
  'errCannotTestPasswordOnPlatform': 'Cannot verify password on this platform',
  'errShellUnsupportedZipEncryption': 'Shell does not support this ZIP encryption format',
  'errCannotRunUnzip': 'Cannot run unzip command',
  'err7zNotFound': '7z command not found',
  'errEmptyZipSources': 'Empty source list for compression',
  'errCannotRunZip': 'Cannot run zip command',
  'errPasswordNeeded': 'Password required',
  'apiPasswordRequired': 'Password required',
  'apiWrongPassword': 'Wrong password',
  'apiCannotListFolder': 'Cannot list folder',
  'apiFileNotFound': 'File not found',
  'apiCannotFolderThumbnail': 'Cannot get folder thumbnail',
  'apiCannotReadFolder': 'Cannot read folder',
  'apiFileTooLargeEdit': 'File too large to edit (>2MB)',
  'apiMissingFolderName': 'Missing folder name',
  'apiMissingFileName': 'Missing file name',
  'apiMissingNewName': 'Missing new name',
  'apiNothingToDelete': 'Nothing to delete',
  'apiCannotWriteFolder': 'Cannot write folder',
  'apiNothingToZip': 'Nothing to compress',
  'apiNotZipFile': 'Not a ZIP file',
  'apiInvalidDestFolder': 'Invalid destination folder',
  'apiMissingFileNameParam': 'Missing file name (name parameter)',
}

err_vi = {
  'errCannotReadZipList': 'Không đọc được danh sách file trong ZIP',
  'errZipTooLargeVerifyPassword': 'ZIP quá lớn ({sizeMb} MB). Không thể xác minh mật khẩu trong bộ nhớ.',
  'errZipAesTooLarge': 'ZIP mã hóa AES quá lớn ({sizeMb} MB). Giới hạn {limitMb} MB.',
  'errZipTooLargeNeedUnzip': 'ZIP quá lớn ({sizeMb} MB). Cần lệnh unzip/7z trên thiết bị.',
  'errFlutterArchiveUnavailable': 'flutter_archive không khả dụng trên nền tảng này',
  'errCannotExtractZipEntry': 'Không trích xuất được mục ZIP',
  'errCannotExtractTar': 'Không thể giải nén TAR',
  'errDataTooLargeCompress': 'Dữ liệu quá lớn ({sizeMb} MB). Không thể nén trong bộ nhớ.',
  'errMultiFolderZipNoCommand': 'Không thể nén nhiều thư mục — thiếu lệnh zip trên thiết bị',
  'errCannotCreateZip': 'Không thể tạo file ZIP',
  'errParentDirNotFound': 'Thư mục cha không tồn tại',
  'errCannotWriteDestDir': 'Không thể ghi vào thư mục đích',
  'errZipTooLargeExtract': 'File ZIP quá lớn ({sizeMb} MB). Cần giải nén native hoặc lệnh unzip.',
  'errZipTooLargeSingleEntry': 'File ZIP quá lớn để trích xuất mục đơn lẻ trong RAM',
  'errZipEntryNotFound': 'Không tìm thấy mục trong ZIP',
  'errFileNotExists': 'File không tồn tại',
  'errInvalidZip': 'File ZIP không hợp lệ',
  'errZipEocdNotFound': 'Không tìm thấy End of Central Directory',
  'errZipCdCorrupt': 'Central Directory ZIP bị hỏng',
  'errZipCdTooLarge': 'Central Directory quá lớn ({sizeMb} MB)',
  'errZipCdIncomplete': 'Không đọc đủ Central Directory',
  'errZip64LocatorInvalid': 'ZIP64 locator không hợp lệ',
  'errZip64EocdInvalid': 'ZIP64 EOCD signature không hợp lệ',
  'errZip64EocdOutOfFile': 'ZIP64 EOCD nằm ngoài file',
  'errDirectoryNotExists': 'Thư mục không tồn tại',
  'errCannotAccessPath': 'Không thể truy cập {path}: {message}',
  'errAlreadyExists': 'Đã tồn tại',
  'errShellListingAndroidOnly': 'Shell listing chỉ hỗ trợ Android',
  'errSuperuserAndroidOnly': 'Chế độ siêu người dùng chỉ hỗ trợ Android',
  'errCannotCheckSuperuser': 'Không thể kiểm tra quyền siêu người dùng',
  'errSuperuserCheckTimeout': 'Hết thời gian kiểm tra quyền siêu người dùng. Thiết bị có thể chưa root hoặc chưa cấp quyền.',
  'errInstallApkAndroidOnly': 'Cài APK chỉ hỗ trợ Android',
  'errApkNotFound': 'Không tìm thấy APK',
  'errApkBackupFailed': 'Backup thất bại',
  'errNoWebServerPassword': 'Chưa có mật khẩu Web Server',
  'errNoPassword': 'Chưa có mật khẩu',
  'errCurrentPasswordWrong': 'Mật khẩu hiện tại không đúng',
  'errBiometricUnlockReason': 'Mở khóa Cope X Studio',
  'errCannotTestPasswordOnPlatform': 'Không thể kiểm tra mật khẩu trên nền tảng này',
  'errShellUnsupportedZipEncryption': 'Shell không hỗ trợ định dạng mã hóa ZIP này',
  'errCannotRunUnzip': 'Không thể chạy lệnh unzip',
  'err7zNotFound': 'Không tìm thấy lệnh 7z',
  'errEmptyZipSources': 'Danh sách nguồn nén trống',
  'errCannotRunZip': 'Không thể chạy lệnh zip',
  'errPasswordNeeded': 'Cần mật khẩu',
  'apiPasswordRequired': 'Cần mật khẩu',
  'apiWrongPassword': 'Mật khẩu sai',
  'apiCannotListFolder': 'Không thể tải thư mục',
  'apiFileNotFound': 'Không tìm thấy file',
  'apiCannotFolderThumbnail': 'Không thể lấy thumbnail của thư mục',
  'apiCannotReadFolder': 'Không thể đọc thư mục',
  'apiFileTooLargeEdit': 'File quá lớn để chỉnh sửa (>2MB)',
  'apiMissingFolderName': 'Thiếu tên thư mục',
  'apiMissingFileName': 'Thiếu tên file',
  'apiMissingNewName': 'Thiếu tên mới',
  'apiNothingToDelete': 'Không có mục để xóa',
  'apiCannotWriteFolder': 'Không thể ghi thư mục',
  'apiNothingToZip': 'Không có mục để nén',
  'apiNotZipFile': 'Không phải file ZIP',
  'apiInvalidDestFolder': 'Thư mục đích không hợp lệ',
  'apiMissingFileNameParam': 'Thiếu tên file (tham số name)',
}

meta = {
  'logUnlockZip': ph(('name', 'String')),
  'logUnlockError': ph(('error', 'String')),
  'logNewTab': ph(('name', 'String')),
  'logFileLocation': ph(('path', 'String')),
  'logViewZip': ph(('name', 'String')),
  'logRecentAdded': ph(('count', 'int')),
  'logRecentScanned': ph(('count', 'int')),
  'logRecentScanError': ph(('error', 'String')),
  'logAppsAdded': ph(('count', 'int'), ('type', 'String')),
  'logAppsLoaded': ph(('count', 'int')),
  'logAppsLoadError': ph(('error', 'String')),
  'logReadItemsRoot': ph(('count', 'int')),
  'logReadItemsAt': ph(('count', 'int'), ('location', 'String')),
  'logReadError': ph(('location', 'String'), ('error', 'String')),
  'logOpenAppInfoError': ph(('error', 'String')),
  'logApkCopied': ph(('name', 'String')),
  'logApkCopyError': ph(('error', 'String')),
  'logApkShared': ph(('name', 'String')),
  'logApkShareError': ph(('error', 'String')),
  'logPlayStoreError': ph(('error', 'String')),
  'logApkBackup': ph(('path', 'String')),
  'logApkBackupError': ph(('error', 'String')),
  'logUninstall': ph(('name', 'String')),
  'logUninstallError': ph(('error', 'String')),
  'logLaunchApp': ph(('package', 'String')),
  'logOpenAppError': ph(('error', 'String')),
  'logHomeLoadError': ph(('error', 'String')),
  'logFtpError': ph(('error', 'String')),
  'logZipReadError': ph(('error', 'String')),
  'logFileOpened': ph(('name', 'String')),
  'logFormatNotSupportedOpen': ph(('format', 'String')),
  'logFtpFileLoadError': ph(('error', 'String')),
  'logCreateFile': ph(('name', 'String')),
  'logCreateFolder': ph(('name', 'String')),
  'logCopiedItems': ph(('count', 'int')),
  'logCutItems': ph(('count', 'int')),
  'logPasteError': ph(('error', 'String')),
  'logDuplicateSuccess': ph(('count', 'int')),
  'logDuplicateError': ph(('error', 'String')),
  'logMovedToTrash': ph(('count', 'int')),
  'logDeletedItems': ph(('count', 'int')),
  'logDeleteError': ph(('error', 'String')),
  'logRenamedTo': ph(('name', 'String')),
  'logZippedTo': ph(('name', 'String')),
  'logUnzipTo': ph(('folder', 'String')),
  'logUnzipError': ph(('error', 'String')),
  'logInstallApkError': ph(('error', 'String')),
  'logShareFileError': ph(('error', 'String')),
  'logFormatNotSupportedDirect': ph(('format', 'String')),
  'logFileSaved': ph(('name', 'String')),
  'logSaveError': ph(('error', 'String')),
  'logWebServerStarted': ph(('auth', 'String'), ('url', 'String'), ('scope', 'String')),
  'logWebServerScopeFolder': ph(('path', 'String')),
  'logWebServerStartError': ph(('error', 'String')),
  'logZipError': ph(('error', 'String')),
  'errZipTooLargeVerifyPassword': ph(('sizeMb', 'String')),
  'errZipAesTooLarge': ph(('sizeMb', 'String'), ('limitMb', 'String')),
  'errZipTooLargeNeedUnzip': ph(('sizeMb', 'String')),
  'errDataTooLargeCompress': ph(('sizeMb', 'String')),
  'errZipTooLargeExtract': ph(('sizeMb', 'String')),
  'errZipCdTooLarge': ph(('sizeMb', 'String')),
  'errCannotAccessPath': ph(('path', 'String'), ('message', 'String')),
}

for lang, log, err in [('en', log_en, err_en), ('vi', log_vi, err_vi)]:
    p = f'lib/l10n/app_{lang}.arb'
    with open(p, encoding='utf-8') as f:
        d = json.load(f)
    d.update(log)
    d.update(err)
    for k in meta:
        if k in d:
            d[f'@{k}'] = meta[k]
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(lang, 'ok')
